#version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: connecticut-homes-dashboard:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - MONGO_COLLECTION_NAME=${MONGO_COLLECTION_NAME}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    command: --replSet rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB}

  streamlit:
    build:
      context: ..
      dockerfile: deployment/streamlit.Dockerfile
    image: connecticut-homes-streamlit:latest
    ports:
      - "8501:8501"
    volumes:
      - ../app:/app
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - MONGO_COLLECTION_NAME=${MONGO_COLLECTION_NAME}
      - API_BASE=http://app:8000
    depends_on:
      - app
    command: streamlit run /app/app_streamlit.py --server.port 8501 --server.address 0.0.0.0

volumes:
  mongo-data:
    driver: local
